name: Rust

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --all-targets
    - name: Run tests
      run: cargo test --all-targets
    - name: Clippy
      run: cargo clippy --all-targets -- -D warnings -D clippy::all -D clippy::cargo
    - name: Check for correct formatting
      run: cargo fmt -- --check --files-with-diff
    - name: Cargo audit
      run: bash -c 'which cargo-audit || cargo install cargo-audit; cargo audit --deny-warnings'
